src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="store_orders")
 */
class Order
{
    public const STATUS_NOT_PROCESSED = 0;
    public const STATUS_IN_PRODUCTION = 1;
    public const STATUS_SENT = 2;

    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var Store
     * @ORM\ManyToOne(targetEntity="Store")
     * @ORM\JoinColumn(name="store_id", referencedColumnName="id", nullable=false)
     */
    protected $store;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $name;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $email;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    protected $phone;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $street;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $zip_code;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $city;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $country;

    /**
     * @var DeliveryType
     * @ORM\ManyToOne(targetEntity="DeliveryType")
     * @ORM\JoinColumn(name="delivery_type_id", referencedColumnName="id", nullable=false)
     */
    protected $delivery_type;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    protected $product_list;

    /**
     * @var int
     * @ORM\Column(type="smallint", options={"default": 0})
     */
    protected $status = 0;

    /**
     * @return int The ID
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Store The store
     */
    public function getStore(): Store
    {
        return $this->store;
    }

    /**
     * @param Store $store The store
     *
     * @return $this
     */
    public function setStore(Store $store): self
    {
        $this->store = $store;

        return $this;
    }

    /**
     * @return string The name
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name The name
     *
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string The email
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email The email
     *
     * @return $this
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return string The phone
     */
    public function getPhone(): string
    {
        return $this->phone;
    }

    /**
     * @param string $phone The phone
     *
     * @return $this
     */
    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return string The street
     */
    public function getStreet(): string
    {
        return $this->street;
    }

    /**
     * @param string $street The street
     *
     * @return $this
     */
    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    /**
     * @return string The zip code
     */
    public function getZipCode(): string
    {
        return $this->zip_code;
    }

    /**
     * @param string $zip_code The zip code
     *
     * @return $this
     */
    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    /**
     * @return string The city
     */
    public function getCity(): string
    {
        return $this->city;
    }

    /**
     * @param string $city The city
     *
     * @return $this
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return string The country
     */
    public function getCountry(): string
    {
        return $this->country;
    }

    /**
     * @param string $country The country
     *
     * @return $this
     */
    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return DeliveryType The delivery type
     */
    public function getDeliveryType(): DeliveryType
    {
        return $this->delivery_type;
    }

    /**
     * @param DeliveryType $delivery_type The delivery type
     *
     * @return $this
     */
    public function setDeliveryType(DeliveryType $delivery_type): self
    {
        $this->delivery_type = $delivery_type;

        return $this;
    }

    /**
     * @return array The product list
     */
    public function getProductList(): array
    {
        return $this->product_list;
    }

    /**
     * @param array $product_list The product list
     *
     * @return $this
     */
    public function setProductList(array $product_list): self
    {
        $this->product_list = $product_list;

        return $this;
    }

    /**
     * @return int The status
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status The status
     *
     * @return $this
     */
    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="store_products")
 */
class Product
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var Store
     * @ORM\ManyToOne(targetEntity="Store", inversedBy="products")
     * @ORM\JoinColumn(name="store_id", referencedColumnName="id", nullable=false)
     */
    protected $store;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id", nullable=false)
     */
    protected $owner;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    protected $name;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    protected $description;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    protected $short_description;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    protected $price;

    /**
     * @var array
     * @ORM\Column(type="array")
     */
    protected $price_sale;

    /**
     * @var string|null
     * @ORM\Column(type="string", nullable=true)
     */
    protected $small_icon;

    /**
     * @var Collection
     * @ORM\OneToMany(
     *     targetEntity="ProductImages",
     *     mappedBy="product",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     */
    protected $images;

    /**
     * @var bool
     * @ORM\Column(type="boolean", options={"default": false})
     */
    protected $downloadable = false;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="ProductFile", mappedBy="product", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $files;

    /**
     * @var int
     * @ORM\Column(type="integer", options={"default": 0})
     */
    protected $stock = 0;

    /**
     * @var DateTime
     * @ORM\Column(type="datetime")
     */
    protected $last_edited;

    /**
     * @var bool
     * @ORM\Column(type="boolean", options={"default": false})
     */
    protected $closed = false;

    /**
     * @var int
     * @ORM\Column(type="integer", options={"default": 0})
     */
    protected $rating_count = 0;

    /**
     * @var float
     * @ORM\Column(type="decimal", options={"default": 0})
     */
    protected $rating_average = 0;

    /**
     * @var Collection
     * @ORM\OneToMany(
     *     targetEntity="ProductRating",
     *     mappedBy="product",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     */
    protected $ratings;

    public function __construct()
    {
        $this->name = new ArrayCollection();
        $this->description = new ArrayCollection();
        $this->short_description = new ArrayCollection();
        $this->price = new ArrayCollection();
        $this->price_sale = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->ratings = new ArrayCollection();
        $this->last_edited = new DateTime();
    }

    /**
     * @return int The ID
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Store The store
     */
    public function getStore(): Store
    {
        return $this->store;
    }

    /**
     * @param Store $store The store
     *
     * @return $this
     */
    public function setStore(Store $store): self
    {
        $this->store = $store;

        return $this;
    }

    /**
     * @return User The owner
     */
    public function getOwner(): User
    {
        return $this->owner;
    }

    /**
     * @param User $owner The owner
     *
     * @return $this
     */
    public function setOwner(User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @param string $language The language
     *
     * @return string|null The name
     */
    public function getName(string $language): ?string
    {
        $array = ($this->name instanceof ArrayCollection ? $this->name : new ArrayCollection($this->name));
        if ($array->containsKey($language)) {
            return $array->get($language);
        }
        if ($array->containsKey($this->getDefaultLanguage())) {
            return $array->get($this->getDefaultLanguage());
        }

        return null;
    }

    /**
     * @return array The names
     */
    public function getNames(): array
    {
        return $this->name;
    }

    /**
     * @param string $name     The name
     * @param string $language The language
     *
     * @return $this
     */
    public function setName(string $name, string $language): self
    {
        $array = ($this->name instanceof ArrayCollection ? $this->name : new ArrayCollection($this->name));
        $array->set($language, $name);
        $this->name = $array->toArray();

        return $this;
    }

    /**
     * @param string $language The language
     *
     * @return $this
     */
    public function removeName(string $language): self
    {
        $array = ($this->name instanceof ArrayCollection ? $this->name : new ArrayCollection($this->name));
        if ($array->containsKey($language)) {
            $array->remove($language);
            $this->name = $array->toArray();
        }

        return $this;
    }

    /**
     * @param string $language The language
     *
     * @return string|null The description
     */
    public function getDescription(string $language): ?string
    {
        $array = ($this->description instanceof ArrayCollection ? $this->description : new ArrayCollection(
            $this->description
        ));
        if ($array->containsKey($language)) {
            return $array->get($language);
        }
        if ($array->containsKey($this->getDefaultLanguage())) {
            return $array->get($this->getDefaultLanguage());
        }

        return null;
    }

    /**
     * @return array The descriptions
     */
    public function getDescriptions(): array
    {
        return $this->description;
    }

    /**
     * @param string $description The description
     * @param string $language    The language
     *
     * @return $this
     */
    public function setDescription(string $description, string $language): self
    {
        $array = ($this->description instanceof ArrayCollection ? $this->description : new ArrayCollection(
            $this->description
        ));
        $array->set($language, $description);
        $this->description = $array->toArray();

        return $this;
    }

    /**
     * @param string $language The language
     *
     * @return $this
     */
    public function removeDescription(string $language): self
    {
        $array = ($this->description instanceof ArrayCollection ? $this->description : new ArrayCollection(
            $this->description
        ));
        if ($array->containsKey($language)) {
            $array->remove($language);
            $this->description = $array->toArray();
        }

        return $this;
    }

    /**
     * @param string $language The language
     *
     * @return string|null The short description
     */
    public function getShortDescription(string $language): ?string
    {
        $array = ($this->short_description instanceof ArrayCollection ? $this->short_description : new ArrayCollection(
            $this->short_description
        ));
        if ($array->containsKey($language)) {
            return $array->get($language);
        }
        if ($array->containsKey($this->getDefaultLanguage())) {
            return $array->get($this->getDefaultLanguage());
        }

        return null;
    }

    /**
     * @return array An array of the short descriptions
     */
    public function getShortDescriptions(): array
    {
        return $this->short_description;
    }

    /**
     * @param string $description The description
     * @param string $language    The language
     *
     * @return $this
     */
    public function setShortDescription(string $description, string $language): self
    {
        $array = ($this->short_description instanceof ArrayCollection ? $this->short_description : new ArrayCollection(
            $this->short_description
        ));
        $array->set($language, $description);
        $this->short_description = $array->toArray();

        return $this;
    }

    /**
     * @param string $language The language
     *
     * @return $this
     */
    public function removeShortDescription(string $language): self
    {
        $array = ($this->short_description instanceof ArrayCollection ? $this->short_description : new ArrayCollection(
            $this->short_description
        ));
        if ($array->containsKey($language)) {
            $array->remove($language);
            $this->short_description = $array->toArray();
        }

        return $this;
    }

    /**
     * @param string $currency The currency
     *
     * @return string|null The price
     */
    public function getPrice(string $currency): ?string
    {
        $array = ($this->price instanceof ArrayCollection ? $this->price : new ArrayCollection($this->price));
        if ($array->containsKey($currency)) {
            return $array->get($currency);
        }
        if ($array->containsKey($this->getDefaultCurrency())) {
            return $array->get($this->getDefaultCurrency());
        }

        return null;
    }

    /**
     * @return array The prices
     */
    public function getPrices(): array
    {
        return $this->price;
    }

    /**
     * @param float  $price    The price
     * @param string $currency The currency
     *
     * @return $this
     */
    public function setPrice(float $price, string $currency): self
    {

templates/theme_admin1/catalogue.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item g-mr-10">
                <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="#!">{{ 'admin.page.catalogue.breadcrumb.shop'|trans }}</a>
                <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
            </li>

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.catalogue.breadcrumb.product'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.catalogue.title'|trans }}</h1>
        <a href="{{ path('store_admin', {'store': current_store.url, 'page': 'create-product'}) }}" class="btn btn-success mb-2">{{ 'admin.page.catalogue.create'|trans }}</a>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>{{ 'admin.page.catalogue.table.name'|trans }}</th>
                    <th>{{ 'admin.page.catalogue.table.sh_desc'|trans }}</th>
                    <th>{{ 'admin.page.catalogue.table.lo_desc'|trans }}</th>
                    <th>{{ 'admin.page.catalogue.table.price'|trans }}</th>
                    <th>{{ 'admin.page.catalogue.table.sale_price'|trans }}</th>
                    <th>{{ 'admin.page.catalogue.table.sm_image'|trans }}</th>
                    <th>{{ 'admin.page.catalogue.table.xl_image'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td>{% for language, item in product.names %}{{ language }} => {{ item }} |{% endfor %}</td>
                        <td>{% for language, item in product.shortDescriptions %}{{ language }} => {{ item }} |{% endfor %}</td>
                        <td>{% for language, item in product.descriptions %}{{ language }} => {{ item }} |{% endfor %}</td>
                        <td>{% for currency, item in product.prices %}{{ currency }} => {{ item }} |{% endfor %}</td>
                        <td>{% if product.salePrices is not null %}{% for currency, item in product.salePrices %}{{ currency }} => {{ item }} |{% endfor %}{% endif %}</td>
                        <td>{{ product.smallIcon }}</td>
                        <td>{% for image in product.images %}{{ image.image }} |{% endfor %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/theme_admin1/create_product.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item g-mr-10">
                <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="#!">{{ 'admin.page.vouchers.breadcrumb.shop'|trans }}</a>
                <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
            </li>

            <li class="list-inline-item g-mr-10">
                <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="{{ path('store_admin', {'store': current_store.url, 'page': 'catalogue'}) }}">{{ 'admin.page.catalogue.breadcrumb.product'|trans }}</a>
                <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
            </li>

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.create_product.title'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.create_product.title'|trans }}</h1>
        <div class="row">
            <div class="col-md-5">
                {{ form_start(add_product_form, {'attr': {'class': 'card'}}) }}
                <div class="card-body">
                    {{ form_errors(add_product_form) }}

                    <div class="form-group row">
                        {{ form_label(add_product_form.name, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(add_product_form.name, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text text-danger">{{ form_errors(add_product_form.name) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(add_product_form.description, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(add_product_form.description, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text text-danger">{{ form_errors(add_product_form.description) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(add_product_form.short_description, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(add_product_form.short_description, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text text-danger">{{ form_errors(add_product_form.short_description) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(add_product_form.price, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(add_product_form.price, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text text-danger">{{ form_errors(add_product_form.price) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(add_product_form.sale_price, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(add_product_form.sale_price, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text text-danger">{{ form_errors(add_product_form.sale_price) }}</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ form_label(add_product_form.stock, null, {'label_attr': {'class': 'col-sm-4 col-form-label'}}) }}
                        <div class="col-sm-8">
                            {{ form_widget(add_product_form.stock, {'attr': {'class': 'form-control form-control-md g-brd-gray-light-v7 g-brd-gray-light-v3--focus g-rounded-4 g-px-14 g-py-10'}}) }}
                            <small class="form-text text-danger">{{ form_errors(add_product_form.stock) }}</small>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    {{ form_widget(add_product_form.send, {'attr': {'class': 'btn u-btn-blue'}}) }}
                </div>
                {{ form_end(add_product_form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/theme_admin1/home.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.home.breadcrumb.home'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.home.title'|trans }}</h1>
    </div>
{% endblock %}

templates/theme_admin1/orders.html.twig
{% extends 'theme_admin1/layout_admin.html.twig' %}

{% block breadcrumb %}
    <div class="g-hidden-sm-down g-bg-gray-light-v8 g-pa-20">
        <ul class="u-list-inline g-color-gray-dark-v6">

            <li class="list-inline-item g-mr-10">
                <a class="u-link-v5 g-color-gray-dark-v6 g-color-lightblue-v3--hover g-valign-middle" href="#!">{{ 'admin.page.orders.breadcrumb.shop'|trans }}</a>
                <i class="hs-admin-angle-right g-font-size-12 g-color-gray-light-v6 g-valign-middle g-ml-10"></i>
            </li>

            <li class="list-inline-item">
                <span class="g-valign-middle">{{ 'admin.page.orders.breadcrumb.order'|trans }}</span>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="g-pa-20">
        <h1 class="g-font-weight-300 g-font-size-28 g-color-black g-mb-40">{{ 'admin.page.orders.title'|trans }}</h1>
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>{{ 'admin.page.orders.table.id'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.products'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.delivery'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.status'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.full_name'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.email'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.phone'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.street_house_nr'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.zip_city'|trans }}</th>
                    <th>{{ 'admin.page.orders.table.country'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for index, order in orders %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>
                            {% for key, product in order.productList %}
                                <span class="dropdown">
                                    <a class="dropdown-toggle show-tooltip" href="#" data-placement="bottom" data-toggle="dropdown"><span class="img-thumbnail"><img src="{{ '/app/store/products_img/' ~ orders_data[index][key].id ~ '/' ~ orders_data[index][key].small_icon }}" height="30" width="30" /> <span class="caret"></span></span></a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-header">{{ 'admin.page.orders.amount'|trans }}</li>
                                        <li><a href="#">{{ product.count }}</a></li>
                                        <li class="dropdown-header">{{ 'admin.page.orders.price'|trans }}</li>
                                        <li><a href="#">
                                            {% if product.salePrices[currency] is not null %}<span style="text-decoration:line-through">{% endif %}
                                                {% if product.prices[currency] == 0 %}
                                                    {{ 'admin.page.orders.free'|trans }}
                                                {% else %}
                                                    {{ product.prices[currency]|number_format(2, '.', '\'') }} {{ currency }}
                                                {% endif %}
                                                {% if product.salePrices[currency] is not null %}</span>{% endif %}
                                            |
                                            {% if product.salePrices[currency] == 0 %}
                                                {{ 'admin.page.orders.free'|trans }}
                                            {% else %}
                                                {{ product.salePrices[currency]|number_format(2, '.', '\'') }} {{ currency }}
                                            {% endif %}
                                        </a></li>
                                        <li class="dropdown-header">{{ 'admin.page.orders.total'|trans }}</li>
                                        <li><a href="#">
                                            {% set product_total_price = orders_data[index][key].price * product.count %}
                                            {% set product_total_price_sale = orders_data[index][key].price_sale * product.count %}
                                            {% if orders_data[index][key].in_sale %}<span style="text-decoration:line-through">{% endif %}
                                                {% if product_total_price == 0 %}
                                                    {{ 'admin.page.orders.free'|trans }}
                                                {% else %}
                                                    {{ product_total_price|number_format(2, '.', '\'') }} $ {# TODO: Make this editable by the user #}
                                                {% endif %}
                                                {% if orders_data[index][key].in_sale %}</span>{% endif %}
                                            |
                                            {% if product_total_price_sale == 0 %}
                                                {{ 'admin.page.orders.free'|trans }}
                                            {% else %}
                                                {{ product_total_price_sale|number_format(2, '.', '\'') }} $ {# TODO: Make this editable by the user #}
                                            {% endif %}
                                        </a></li>
                                    </ul>
                                </span>
                            {% endfor %}
                        </td>
                        <td>{{ order.deliveryType }}</td>
                        <td>
                            {% if order.status == 0 %}
                                <span class="text-danger">{{ 'admin.page.orders.status.not_processed'|trans }}</span> <a href="{{ path('store_admin', {'store': current_store.url, 'page': 'change_order_statement_to_1', 'order_id': order.id}) }}" class="btn btn-xs btn-warning">{{ 'admin.page.orders.status.process'|trans }}</a>
                            {% elseif order.status == 1 %}
                                <span class="text-warning">{{ 'admin.page.orders.status.not_sent'|trans }}</span> <a href="{{ path('store_admin', {'store': current_store.url, 'page': 'change_order_statement_to_2', 'order_id': order.id}) }}" class="btn btn-xs btn-success">{{ 'admin.page.orders.status.send'|trans }}</a>
                            {% elseif order.status == 2 %}
                                <span class="text-success">{{ 'admin.page.orders.status.sent'|trans }}</span>
                            {% endif %}
                        </td>
                        <td>{{ order.name }}</td>
                        <td>{{ order.email }}</td>
                        <td>{{ order.phone }}</td>
                        <td>{{ order.street }}</td>
                        <td>{{ order.zipCode }} {{ order.city }}</td>
                        <td>{{ order.country }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}